export const LOGIN_INIT = "LOGIN_INIT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const TEST_INIT = "TEST_INIT";
export const TEST_SUCCESS = "TEST_SUCCESS";
export const TEST_FAIL = "TEST_FAIL";

export const GET_ANALYTICS_INIT = "GET_ANALYTICS_INIT";
export const GET_ANALYTICS_SUCCESS = "GET_ANALYTICS_SUCCESS";
export const GET_ANALYTICS_FAIL = "GET_ANALYTICS_FAIL";

export const GET_USER_INIT = "GET_USER_INIT";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

export const ADD_PROJECT_INIT = "ADD_PROJECT_INIT";
export const ADD_PROJECT_SUCCESS = "ADD_PROJECT_SUCCESS";
export const ADD_PROJECT_FAIL = "ADD_PROJECT_FAIL";

export const GET_PROJECT_INIT = "GET_PROJECT_INIT";
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS";
export const GET_PROJECT_FAIL = "GET_PROJECT_FAIL";

export const ADD_TASK_INIT = "ADD_TASK_INIT";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_FAIL = "ADD_TASK_FAIL";

export const GET_TASK_INIT = "GET_TASK_INIT";
export const GET_TASK_SUCCESS = "GET_TASK_SUCCESS";
export const GET_TASK_FAIL = "GET_TASK_FAIL";

export const UPDATE_TASK_INIT = "UPDATE_TASK_INIT";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_FAIL = "UPDATE_TASK_FAIL";

export const GET_TIME_LOG_INIT = "GET_TIME_LOG_INIT";
export const GET_TIME_LOG_SUCCESS = "GET_TIME_LOG_SUCCESS";
export const GET_TIME_LOG_FAIL = "GET_TIME_LOG_FAIL";
export const ADD_TIME_LOG_INIT = "ADD_TIME_LOG_INIT";
export const ADD_TIME_LOG_SUCCESS = "ADD_TIME_LOG_SUCCESS";
export const ADD_TIME_LOG_FAIL = "ADD_TIME_LOG_FAIL";
